# Generated by Django 5.0.3 on 2024-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('emp_code', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
            ],
        ),
    ]
