# Generated by Django 4.2.11 on 2024-03-29 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('birthday', models.DateField(default=datetime.datetime(2024, 3, 29, 5, 37, 14, 278787))),
                ('website', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
